
# Site settings
title: Jesse Blog
email: qiuzhihui1990@163.com
description: "修和无人见，存心有天知。"
url: "http://qiuzhihui1990.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

# SNS settings
RSS: false
github_username:  qiuzhihui1990
jianshu_username: qiuzhihui1990

# Build settings
paginate: 10              # 一页你准备放几篇文章

# markdown
markdown: kramdown
theme: jekyll-theme-merlot
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
